### ISSUE TITLE
Add information about reading this book offline

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-app-guide#2]
When I'm on a slow/nonexistent internet connection, I like having all my stuff on my local computer so I can access it easily... I couldn't find any info on this in the book, and it wasn't until I read "contributing to these docs" that I found this GitHub repo.

I guess at minimum, one could just clone this repo and read its markdown files directly to view the docs, but is there an easy way to get the [pretty version](http://webmaker-mobile-guide.mofodev.net/) on one's local computer without an internet connection?

**Comment by k88hudson** [comment]
There are actually epub/mobi versions of these docs that get published, we need to link to them though.

I am closing issues here since I have merged docs into the main repo, but i will copy this issue over
